### Produce to Kafka (via Rest API) to an trigger exception in the consumer.

POST http://localhost:8080/api/quotes
Content-Type: application/json

{
  "symbol": "KABOOM",
  "exchange": "AMS",
  "tradeValue": "101.99",
  "currency": "EUR",
  "description": "Trigger exception!"
}